# Generated by Django 4.0.5 on 2022-06-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_alter_flight_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['aeroplane', 'departure_datetime']},
        ),
    ]
