# Generated by Django 4.0.5 on 2022-07-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
