# Generated by Django 4.0.5 on 2022-06-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
