# Generated by Django 4.0.5 on 2022-06-29 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passenger_first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='passenger_last_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger',
            field=models.ManyToManyField(related_name='passengers', to=settings.AUTH_USER_MODEL),
        ),
    ]
